### ISSUE TITLE
Add support for CLI

### ISSUE THREAD

**Issue by abakermi** [ChetanXpro/VideoSanitizer#2]
@ChetanXpro Can we add cli and refactor the code to be more modular

**Comment by ChetanXpro** [comment]
> @ChetanXpro Can we add cli and refactor the code to be more modular

Thanks for the suggestion! Adding CLI and code refactoring are on the roadmap. I'll keep you posted on the progress.

**Comment by ChetanXpro** [comment]
@abakermi  Feel free to take on the CLI addition and code refactoring. If you have any questions or need assistance, don't hesitate to reach out. I appreciate your collaboration!

**Comment by abakermi** [comment]
@ChetanXpro ok

**Comment by ChetanXpro** [comment]
Hey @abakermi , are you working on this ?
